name: my_workflow

on:
  workflow_dispatch:

env:
  name: denith

jobs:
  my_first_job:
    runs-on: windows-latest
    steps:
      - name: Print name
        run: echo "my name is $name"

           
